/* ================= worlds ================= */
// ui (optional) – the buttons and touch habits of a world:
//   hint/undo: show 💡 / ↩   act:[icon,label]: the action button   key: Space/Enter does the action
//   tapMe: tapping her own cell does the action   step: a tap moves one cell (no running down the corridor)
//   still: the board is the game, so the character is not drawn
const WORLDS=[
  {id:'ice',ui:{hint:1},name:'ממלכת הקרח',short:'הקרח',rule:'על הקרח מחליקים עד שנתקעים בסלע או בקצה. תכנני את הדרך אל בית הקרח!',
   color:'var(--ice)',hex:'#5bb8e8',deep:'#2f86b8',goal:drawIgloo,goalName:'בית הקרח',
   levels:[{n:6,min:3,rock:.15},{n:7,min:4,rock:.16},{n:8,min:5,rock:.17},{n:9,min:6,rock:.18},{n:10,min:7,rock:.18},{n:11,min:8,rock:.19}],
   stickers:['⛄','🐻‍❄️','❄️','🦭','🧊','🏔️']},
  {id:'castle',name:'הטירה הקסומה',short:'הטירה',rule:'כל דלת צבעונית נפתחת רק עם המפתח באותו צבע. מצאי את המפתחות והגיעי אל הכתר!',
   color:'var(--castle)',hex:'#7b5ea7',deep:'#563e7e',goal:drawCrown,goalName:'הכתר',
   levels:[{n:8,doors:1},{n:9,doors:1},{n:10,doors:2},{n:11,doors:2},{n:12,doors:3},{n:13,doors:3}],
   stickers:['🏰','🐉','🧚','👸','🗝️','🦄']},
  {id:'sea',name:'מתחת לים',short:'הים',rule:'האוויר יורד עם כל צעד. שחי דרך הבועות כדי למלא אוויר, והיזהרי מהדגים!',
   color:'var(--sea)',hex:'#1a9ba1',deep:'#0f6f74',goal:drawChest,goalName:'תיבת האוצר',
   levels:[{n:8,air:28,fish:0,speed:850},{n:9,air:27,fish:2,speed:820},{n:10,air:26,fish:2,speed:790},{n:11,air:25,fish:3,speed:760},{n:12,air:24,fish:3,speed:730},{n:13,air:23,fish:4,speed:700}],
   stickers:['🐬','🐠','🦀','🐙','🐚','🧜‍♀️']},
  {id:'jungle',name:'הג׳ונגל',short:'הג׳ונגל',rule:'גשר חבלים נופל אחרי שעוברים עליו, אז קודם אוספים את הכוכבים! והיזהרי מהקופים, הם חוטפים כוכבים.',
   color:'#3a9d5d',hex:'#3a9d5d',deep:'#276e40',goal:drawBananas,goalName:'אשכול הבננות',
   levels:[{n:9,bridges:2,monkeys:0,speed:880},{n:10,bridges:2,monkeys:1,speed:850},{n:11,bridges:3,monkeys:2,speed:820},{n:12,bridges:3,monkeys:2,speed:790},{n:13,bridges:4,monkeys:3,speed:760},{n:14,bridges:4,monkeys:3,speed:730}],
   stickers:['🦜','🐯','🐘','🦒','🍍','🦥']},
  {id:'space',name:'החלל',short:'החלל',rule:'כל פורטל מעביר אותך לפורטל באותו צבע בצד אחר של המבוך. מצאי את הדרך אל החללית!',
   color:'#3b2f7a',hex:'#3b2f7a',deep:'#241b52',goal:drawRocket,goalName:'החללית',
   levels:[{n:9,pairs:1,decoys:0},{n:10,pairs:1,decoys:1},{n:11,pairs:2,decoys:1},{n:12,pairs:2,decoys:2},{n:13,pairs:3,decoys:2},{n:14,pairs:3,decoys:3}],
   stickers:['🪐','🌙','🌟','🛸','👩‍🚀','☄️']},
  {id:'candy',ui:{step:1},name:'מפעל הממתקים',short:'המפעל',rule:'מסועים מסיעים אותך לכיוון החץ. כשעולים על לחצן, השערים הוורודים והתכולים מתחלפים: הסגורים נפתחים והפתוחים נסגרים.',
   color:'#e56b9f',hex:'#e56b9f',deep:'#b8467a',goal:drawCake,goalName:'העוגה',
   levels:[{n:8,conv:2,gA:1,gB:1,sw:1,loops:3},{n:9,conv:3,gA:1,gB:1,sw:1,loops:4},{n:10,conv:3,gA:1,gB:2,sw:2,loops:5},{n:11,conv:4,gA:2,gB:2,sw:2,loops:5},{n:12,conv:5,gA:2,gB:3,sw:2,loops:6},{n:13,conv:6,gA:2,gB:3,sw:3,loops:6}],
   stickers:['🍭','🧁','🍩','🍫','🍬','🍦']},
  {id:'farm',name:'החווה',short:'החווה',rule:'אפרוחים אבודים מצטרפים אלייך ועוקבים אחרייך בשורה. אספי את כולם והביאי אותם לתרנגולת. כשהשועל ער, הוא מבהיל את האפרוח האחרון.',
   color:'#d9a441',hex:'#d9a441',deep:'#a8792a',goal:drawHen,goalName:'התרנגולת',
   levels:[{n:8,chicks:2,fox:0,speed:900},{n:9,chicks:3,fox:1,speed:880},{n:10,chicks:3,fox:1,speed:860},{n:11,chicks:4,fox:2,speed:840},{n:12,chicks:5,fox:2,speed:820},{n:13,chicks:6,fox:3,speed:800}],
   stickers:['🐄','🐷','🐴','🐑','🌻','🚜']},
  {id:'rainbow',name:'עולם הקשת',short:'הקשת',rule:'דלי צבע צובע אותך. על רצפה צבעונית עוברים רק כשאת באותו צבע, אז צריך לתכנן באיזה סדר להחליף צבעים.',
   color:'linear-gradient(100deg,#ff595e,#ffca3a 30%,#8ac926 55%,#1982c4 80%,#6a4c93)',hex:'#6a4c93',deep:'#4b3569',goal:drawRainbowEnd,goalName:'סוף הקשת',
   levels:[{n:8,gates:1,colors:1,extra:1,loops:3},{n:9,gates:2,colors:2,extra:2,loops:4},{n:10,gates:2,colors:2,extra:3,loops:5},{n:11,gates:3,colors:3,extra:3,loops:5},{n:12,gates:3,colors:3,extra:4,loops:6},{n:13,gates:4,colors:4,extra:4,loops:6}],
   stickers:['🌈','🦋','🌸','🎨','🌷','✨']},
  {id:'toys',ui:{undo:1},name:'מחסן הצעצועים',short:'המחסן',rule:'ארגזי צעצועים חוסמים את הדרך. אפשר לדחוף אותם, אבל רק אחד בכל פעם ולא לתוך קיר. נתקעת? יש כפתור "צעד אחורה".',
   color:'#c07f4c',hex:'#c07f4c',deep:'#8f5a31',goal:drawBall,goalName:'הכדור הצבעוני',
   levels:[{n:7,shelves:1,gaps:1,rock:.08,extra:1,min:8},{n:8,shelves:2,gaps:1,rock:.08,extra:0,min:10},{n:8,shelves:2,gaps:2,rock:.1,extra:1,min:12},{n:9,shelves:2,gaps:2,rock:.12,extra:2,min:14},{n:11,shelves:3,gaps:1,rock:.1,extra:1,min:18},{n:11,shelves:3,gaps:2,rock:.12,extra:2,min:20}],
   stickers:['🧸','🪀','🪁','🎲','🧩','🎈']},
  {id:'forest',ui:{step:1},name:'יער הקסמים',short:'היער',rule:'פטרייה סגולה הופכת את החצים: למעלה נהיה למטה וימינה נהיה שמאלה, עד הפטרייה הבאה.',
   color:'#6a994e',hex:'#6a994e',deep:'#436b30',goal:drawFairyHouse,goalName:'בית הפיות',
   levels:[{n:8,onPath:1,extra:1},{n:9,onPath:2,extra:1},{n:10,onPath:2,extra:2},{n:11,onPath:3,extra:2},{n:12,onPath:3,extra:3},{n:13,onPath:4,extra:3}],
   stickers:['🦉','🍄','🐿️','🌳','🦔','🐌']},
  {id:'beach',name:'חוף הים',short:'החוף',rule:'הגלים עולים ויורדים ומכסים חלק מהחול. מחכים שהמים יירדו ורצים!',
   color:'#2a9fd6',hex:'#2a9fd6',deep:'#1c6f99',goal:drawSandcastle,goalName:'ארמון החול',
   levels:[{n:8,bands:1,extra:1,speed:800},{n:9,bands:2,extra:1,speed:760},{n:10,bands:2,extra:2,speed:720},{n:11,bands:3,extra:2,speed:680},{n:12,bands:3,extra:3,speed:640},{n:13,bands:4,extra:3,speed:600}],
   stickers:['🏖️','🐢','🦩','🐳','🌴','⛱️']},
  {id:'mirror',ui:{step:1},name:'ארמון המראות',short:'המראות',rule:'את והבבואה שלך זזות יחד, אבל הבבואה זזה הפוך ימינה-שמאלה. כל אחת צריכה להגיע למראה שלה.',
   color:'#9d8ec4',hex:'#9d8ec4',deep:'#6f5fa0',goal:drawMirrorGoal,goalName:'המראות',
   levels:[{n:6,loops:3},{n:7,loops:3},{n:8,loops:4},{n:9,loops:4},{n:10,loops:5},{n:11,loops:5}],
   stickers:['🪞','💍','🦢','👗','💫','🔮']},
  {id:'haunt',name:'הבית המפחיד',short:'הרוחות',rule:'חשוך בבית! הפנס נחלש עם כל צעד, וסוללה ממלאת אותו. הרוחות חמודות, וכשהן ישנות לא מפריעות.',
   color:'#4a3b73',hex:'#4a3b73',deep:'#2e2450',goal:drawPumpkin,goalName:'הדלעת החייכנית',
   levels:[{n:8,bat:24,ghosts:0,speed:850},{n:9,bat:22,ghosts:1,speed:820},{n:10,bat:20,ghosts:1,speed:800},{n:11,bat:18,ghosts:2,speed:780},{n:12,bat:17,ghosts:2,speed:760},{n:13,bat:16,ghosts:3,speed:740}],
   stickers:['👻','🎃','🦇','🕯️','🧹','🕰️']},
  {id:'numbers',name:'עולם המספרים',short:'המספרים',rule:'עונים על השאלה שלמעלה ועולים על התשובה הנכונה כדי לעבור. את הכיתה בוחרים בהגדרות ⚙️.',
   color:'#f3722c',hex:'#f3722c',deep:'#b8521a',goal:drawTrophy,goalName:'גביע המספרים',
   levels:[{n:7,kind:'seq',q:3},{n:8,kind:'ex',q:3},{n:9,kind:'prop',q:3},{n:9,kind:'wallet',coins:4},{n:10,kind:'ex',q:5},{n:11,kind:'mix',q:5}],
   stickers:['🔢','➕','➗','🧮','📏','💯']},
  {id:'english',name:'עולם האנגלית',short:'אנגלית',rule:'עונים על השאלה שלמעלה. כל תשובה מופיעה בצבע אחר, ועולים על המשבצת בצבע של התשובה הנכונה.',
   color:'#3a86ff',hex:'#3a86ff',deep:'#2560b8',goal:drawABC,goalName:'קוביות ה־ABC',
   levels:[{n:7,kind:'pic',q:3},{n:7,kind:'word2pic',q:3},{n:8,kind:'spell',q:3},{n:8,kind:'opp',q:4},{n:9,kind:'mix',q:5},{n:10,kind:'mix',q:5}],
   stickers:['🔤','🎒','✏️','🗽','🚕','☕']},
  {id:'hebrew',name:'עולם העברית',short:'עברית',rule:'עונים על השאלה שלמעלה: אותיות, מילים, הפכים ועוד. עולים על המשבצת בצבע של התשובה הנכונה.',
   color:'#e5383b',hex:'#e5383b',deep:'#a4161a',goal:drawBook,goalName:'ספר הקסמים',
   levels:[{n:7,kind:'first',q:3},{n:7,kind:'missing',q:3},{n:8,kind:'plural',q:3},{n:8,kind:'opp',q:4},{n:9,kind:'mix',q:5},{n:10,kind:'mix',q:5}],
   stickers:['📚','🖋️','🍯','🌿','🐪','🎻']},
  {id:'logic',name:'עולם החידות',short:'חידות',rule:'דפוסים, מי לא שייך, מה מתאים וחידות. חושבים רגע ועולים על התשובה הנכונה.',
   color:'#8338ec',hex:'#8338ec',deep:'#5a22a8',goal:drawPuzzle,goalName:'חתיכת הפאזל',
   levels:[{n:7,kind:'pattern',q:3},{n:7,kind:'odd',q:3},{n:8,kind:'analogy',q:3},{n:8,kind:'most',q:4},{n:9,kind:'mix',q:5},{n:10,kind:'mix',q:5}],
   stickers:['🧩','💡','🔍','♟️','🎯','🔭']},
  {id:'munch',name:'מבוך הנקודות',short:'הנקודות',rule:'אוכלים את כל הנקודות, ואז השער אל הדובדבנים נפתח. היזהרי מהבלובים! תות כוח 🍓 הופך אותם לפחדנים, ואז אפשר לתפוס אותם ולשלוח אותם הביתה.',
   color:'#2b2b8f',hex:'#2b2b8f',deep:'#16165a',goal:drawCherry,goalName:'הדובדבנים',
   levels:[{n:6,blobs:1,speed:950,power:2,powerMs:7000,chase:.1},{n:7,blobs:1,speed:900,power:2,powerMs:7000,chase:.15},{n:7,blobs:2,speed:880,power:2,powerMs:6500,chase:.15},{n:8,blobs:2,speed:840,power:2,powerMs:6500,chase:.2},{n:8,blobs:3,speed:800,power:3,powerMs:6000,chase:.2},{n:9,blobs:3,speed:760,power:3,powerMs:6000,chase:.25}],
   stickers:['🍒','👾','🕹️','🍓','🫐','🏅']},
  {id:'snake',ui:{undo:1},name:'גינת הנחש',short:'הנחש',rule:'כל פרי מאריך לך את הזנב, ואי אפשר לעבור דרכו. אוכלים את כל הפירות ומגיעים אל הקן. נתקעת? יש כפתור "צעד אחורה".',
   color:'#5a8f29',hex:'#5a8f29',deep:'#306230',goal:drawNest,goalName:'הקן',
   levels:[{n:6,fruits:3,rock:.06,steps:26},{n:6,fruits:4,rock:.08,steps:32},{n:7,fruits:4,rock:.08,steps:38},{n:7,fruits:5,rock:.1,steps:44},{n:8,fruits:6,rock:.1,steps:52},{n:8,fruits:7,rock:.12,steps:60}],
   stickers:['🐍','🍏','🥚','🪺','🍐','🐛']},
  {id:'road',name:'הכביש והנהר',short:'הכביש',rule:'חוצים את הכביש ברווחים שבין המכוניות. בנהר קופצים על בולי עץ, והם לוקחים אותך איתם. הגיעי אל עלה הלוטוס בצד השני!',
   color:'#3f8f4f',hex:'#3f8f4f',deep:'#2a6336',goal:drawLily,goalName:'עלה הלוטוס',
   levels:[{n:7,road:2,river:0,dens:.3,speed:950},{n:7,road:3,river:0,dens:.35,speed:900},{n:8,road:2,river:1,dens:.35,speed:900},{n:9,road:2,river:2,dens:.35,speed:850},{n:10,road:3,river:2,dens:.4,speed:820},{n:11,road:3,river:3,dens:.4,speed:780}],
   stickers:['🚗','🐸','🪵','🚌','🚦','🦆']},
  {id:'bomb',ui:{act:['🎆','לשים זיקוק'],key:1,tapMe:1},name:'מבוך הזיקוקים',short:'הזיקוקים',rule:'שמים זיקוק 🎆 ליד קיר סדוק ומתרחקים. הזיקוק מפוצץ קירות סדוקים לכל הכיוונים. מאחורי הקירות מסתתרים כוכבים, ובסוף מחכה הדלת. היזהרי מהבלונים!',
   color:'#e07a1f',hex:'#e07a1f',deep:'#a85710',goal:drawExitDoor,goalName:'הדלת',
   levels:[{n:7,crack:.3,foes:0,range:2,fuse:2000,speed:950},{n:7,crack:.4,foes:1,range:2,fuse:2000,speed:950},{n:9,crack:.4,foes:1,range:2,fuse:1900,speed:900},{n:9,crack:.5,foes:2,range:2,fuse:1900,speed:880},{n:11,crack:.5,foes:2,range:2,fuse:1800,speed:850},{n:11,crack:.55,foes:3,range:2,fuse:1800,speed:820}],
   stickers:['🎆','🎇','💥','🧱','🎉','🎈']},
  {id:'ladders',ui:{act:['🦘','לקפוץ'],key:1,tapMe:1},name:'מגדל הסולמות',short:'הסולמות',rule:'רואים את המגדל מהצד. הולכים על הקומות, מטפסים בסולמות ונופלים דרך חורים. חבית מתגלגלת? קופצים מעליה בחץ למעלה או בכפתור 🦘, בדיוק כשהיא מתקרבת. נגעת בחבית? חוזרים אחורה. הגיעי אל הדגל שבראש המגדל!',
   color:'#c0392b',hex:'#c0392b',deep:'#8e2a20',goal:drawFlag,goalName:'הדגל',
   levels:[{n:7,barrels:0,gaps:0,speed:850},{n:8,barrels:1,gaps:1,speed:850},{n:10,barrels:1,gaps:1,speed:820},{n:10,barrels:2,gaps:2,speed:800},{n:13,barrels:2,gaps:2,speed:780},{n:13,barrels:3,gaps:3,speed:750}],
   stickers:['🪜','🛢️','🏗️','🔨','🚩','🧗']},
  {id:'mines',name:'שדה החפרפרות',short:'החפרפרות',rule:'חפרפרות חפרו בורות נסתרים בשדה. כל מספר אומר כמה בורות יש ממש ליד המשבצת: למעלה, למטה, ימינה ושמאלה. היעזרי במספרים והגיעי אל הגזר!',
   color:'#7cb342',hex:'#7cb342',deep:'#4f7a24',goal:drawCarrot,goalName:'הגזר',
   levels:[{n:6,holes:.1},{n:7,holes:.12},{n:7,holes:.15},{n:8,holes:.15},{n:9,holes:.17},{n:10,holes:.18}],
   stickers:['🥕','🕳️','🌾','🌱','🧤','🔦']},
  {id:'deep',name:'מעמקי הים',short:'המעמקים',rule:'צדף קפיצי 🐚 מעיף אותך מעל הקיר. קיפודי ים מוציאים קוצים, אז מחכים שייכנסו. מפלצת ער בולעת אותך למערבולת שמחזירה אותך אחורה. צדף מהירות ⚡ נותן לך לשחות מהר!',
   color:'#14507a',hex:'#14507a',deep:'#0a2f4d',goal:drawPearl,goalName:'הפנינה',
   levels:[{n:7,pads:1,spikes:0,monsters:0,boosts:0,speed:750},{n:8,pads:1,spikes:2,monsters:1,boosts:1,speed:720},{n:9,pads:2,spikes:2,monsters:1,boosts:1,speed:700},{n:10,pads:2,spikes:3,monsters:2,boosts:2,speed:680},{n:11,pads:3,spikes:3,monsters:2,boosts:2,speed:660},{n:12,pads:3,spikes:4,monsters:3,boosts:2,speed:640}],
   stickers:['🦈','🪸','🐡','🦑','🌀','🫧']},
  {id:'geometry',name:'עולם הגיאומטריה',short:'גיאומטריה',rule:'צורות, צלעות, היקף, שטח וזוויות. מסתכלים על הציור למעלה ועולים על התשובה הנכונה. את הכיתה בוחרים בהגדרות ⚙️.',
   color:'#00a6a6',hex:'#00a6a6',deep:'#007272',goal:drawSetSquare,goalName:'הסרגל',
   levels:[{n:7,kind:'name',q:3},{n:7,kind:'sides',q:3},{n:8,kind:'count',q:3},{n:8,kind:'measure',q:4},{n:9,kind:'mix',q:5},{n:10,kind:'mix',q:5}],
   stickers:['📐','📏','🔺','🟦','⭕','🧭']},
  {id:'soccer',ui:{hint:1,undo:1},name:'אצטדיון הכדורגל',short:'כדורגל',rule:'הולכים אל הכדור ⚽ ונכנסים בו כדי לבעוט. הוא מתגלגל עד שמשהו עוצר אותו. כשעומדים ליד הכדור רואים קו שמראה לאן יתגלגל, וכוכב צהוב אומר: גוֹל! נתקעת? יש רמז 💡 וצעד אחורה ↩.',
   color:'#2e7d32',hex:'#2e7d32',deep:'#1b5e20',goal:drawNetGoal,goalName:'השער',
   levels:[{n:7,cones:.08,defs:0,min:2,speed:900},{n:7,cones:.12,defs:0,min:3,speed:880},{n:8,cones:.12,defs:1,min:3,speed:860},{n:9,cones:.14,defs:1,min:4,speed:820},{n:9,cones:.16,defs:2,min:4,speed:790},{n:10,cones:.16,defs:2,min:5,speed:760}],
   stickers:['⚽','🥅','🧤','🏟️','👟','🏆']},
  {id:'hoops',ui:{act:['🏀','לזרוק'],key:1,tapMe:1},name:'מגרש הכדורסל',short:'כדורסל',rule:'עומדים בקו ישר מול סל, בלי קיר באמצע, ולוחצים על הכפתור הכתום 🏀. כשהחץ ירוק, הזריקה תיכנס! אפשר גם לעמוד על הסל ולהטביע. אחרי כל זריקה מרימים את הכדור.',
   color:'#d35400',hex:'#d35400',deep:'#a04000',goal:drawHoopGoal,goalName:'היציאה',
   levels:[{n:7,baskets:2,defs:0,speed:900},{n:8,baskets:2,defs:1,speed:880},{n:9,baskets:3,defs:1,speed:850},{n:10,baskets:3,defs:2,speed:820},{n:11,baskets:4,defs:2,speed:790},{n:12,baskets:4,defs:3,speed:760}],
   stickers:['🏀','⛹️‍♀️','🎽','📣','🥇','🔥']},
  {id:'ski',name:'מסלול הסקי',short:'סקי',rule:'המדרון מושך אותך למטה כל הזמן! זזים ימינה ושמאלה, עוברים בין כל הדגלים 🚩 ונזהרים מהעצים. פספסת שער? הרכבל מעלה אותך שוב.',
   color:'#4a90d9',hex:'#4a90d9',deep:'#2f6aa8',goal:drawLodge,goalName:'הבקתה',
   levels:[{n:8,trees:.08,gates:2,gw:3,lat:3,speed:950},{n:9,trees:.1,gates:2,gw:3,lat:3,speed:900},{n:10,trees:.12,gates:3,gw:2,lat:3,speed:850},{n:11,trees:.13,gates:3,gw:2,lat:2,speed:800},{n:12,trees:.14,gates:4,gw:2,lat:2,speed:760},{n:13,trees:.15,gates:4,gw:2,lat:2,speed:720}],
   stickers:['⛷️','🎿','🏔️','❄️','🚡','🧣']},
  {id:'swim',name:'בריכת השחייה',short:'שחייה',rule:'מרוץ! עוברים בין החבלים רק ברווחים, ומגיעים לקיר הכחול לפני השחיינית האחרת. היא יוצאת לדרך כשאת זזה.',
   color:'#0096c7',hex:'#0096c7',deep:'#006d8f',goal:drawMedal,goalName:'קיר הסיום',
   levels:[{n:7,gaps:2,dividers:2,rival:950},{n:8,gaps:2,dividers:3,rival:850},{n:9,gaps:2,dividers:4,rival:760},{n:10,gaps:1,dividers:5,rival:680},{n:11,gaps:1,dividers:6,rival:620},{n:12,gaps:1,dividers:7,rival:570}],
   stickers:['🏊‍♀️','🥽','🦆','🌊','🩱','🏅']},
  {id:'tennis',name:'מגרש הטניס',short:'טניס',rule:'הכדור 🎾 קופץ באלכסון ומשתנה כיוון כשהוא פוגע בקיר. עומדים בדרך שלו כדי להחזיר אותו! אחרי מספיק חבטות היציאה נפתחת.',
   color:'#2a9d8f',hex:'#2a9d8f',deep:'#1f7a70',goal:drawRacket,goalName:'היציאה',
   levels:[{n:7,cones:.04,hits:2,speed:680},{n:8,cones:.06,hits:3,speed:640},{n:8,cones:.08,hits:3,speed:600},{n:9,cones:.08,hits:4,speed:560},{n:10,cones:.1,hits:4,speed:520},{n:10,cones:.12,hits:5,speed:490}],
   stickers:['🎾','🏸','🧢','🍋','🎯','🥤']},
  {id:'hurdles',ui:{act:['🦘','לקפוץ'],key:1,tapMe:1},name:'מסלול המכשולים',short:'מכשולים',rule:'רצים נגד השעון ⏱! רצים אל משוכה וקופצים מעליה לבד (או בכפתור 🦘). בוץ תוקע אותך ללחיצה אחת. השעון מתחיל כשזזים.',
   color:'#c0522b',hex:'#c0522b',deep:'#8e3a1c',goal:drawStopwatch,goalName:'קו הסיום',
   levels:[{n:7,hurdles:1,mud:0,msPer:760},{n:8,hurdles:2,mud:2,msPer:700},{n:9,hurdles:2,mud:3,msPer:650},{n:10,hurdles:3,mud:3,msPer:600},{n:11,hurdles:3,mud:4,msPer:560},{n:12,hurdles:4,mud:5,msPer:520}],
   stickers:['🏃‍♀️','⏱️','👟','🥈','🏁','💨']},
  {id:'golf',ui:{hint:1},name:'מיני גולף',short:'גולף',rule:'כל לחיצה היא חבטה: הכדור ⛳ מתגלגל עד שהוא נעצר בשיח. חול עוצר אותו, ומים מחזירים אותו אחורה. כמה שפחות חבטות, יותר כוכבים!',
   color:'#52b788',hex:'#52b788',deep:'#2d6a4f',goal:drawGolfFlag,goalName:'הגומה',
   levels:[{n:6,bush:.1,sand:0,water:0,min:2},{n:7,bush:.12,sand:.07,water:.04,min:3},{n:7,bush:.14,sand:.08,water:.05,min:3},{n:8,bush:.14,sand:.08,water:.06,min:4},{n:9,bush:.15,sand:.09,water:.07,min:6},{n:9,bush:.16,sand:.1,water:.08,min:7}],
   stickers:['⛳','🏌️‍♀️','🐿️','🌳','🕳️','🎖️']},
  {id:'dojo',ui:{hint:1},name:'אולם הג׳ודו',short:'ג׳ודו',rule:'מזרנים כחולים ואדומים נפתחים לסירוגין: בכל צעד הצבע הפתוח מתחלף. על לבן אפשר תמיד. יריבה בדרך? נכנסים בה ומפילים אותה! 🥋',
   color:'#6a4c93',hex:'#6a4c93',deep:'#4b3569',goal:drawBelt,goalName:'החגורה השחורה',
   levels:[{n:6,posts:.08,color:.3,opp:0,min:8,speed:900},{n:7,posts:.08,color:.4,opp:0,min:10,speed:880},{n:7,posts:.1,color:.5,opp:1,min:10,speed:860},{n:8,posts:.1,color:.55,opp:1,min:12,speed:830},{n:9,posts:.1,color:.6,opp:2,min:14,speed:800},{n:9,posts:.12,color:.65,opp:2,min:16,speed:770}],
   stickers:['🥋','🎌','🍙','🌸','🥉','🙇']},
  {id:'tilt',ui:{hint:1,undo:1},name:'מבוך ההטיה',short:'הטיה',rule:'כל לחיצה מטה את כל הלוח: את והסלעים מתגלגלים עד שמשהו עוצר. סלע יכול לעצור אותך במקום הנכון! מגיעים אל החור הזוהר. יש רמז 💡 וצעד אחורה ↩.',
   color:'#9a8c98',hex:'#9a8c98',deep:'#4a4e69',goal:drawHoleGoal,goalName:'החור הזוהר',
   levels:[{n:6,walls:.12,boulders:0,min:3},{n:6,walls:.14,boulders:1,min:4},{n:7,walls:.14,boulders:1,min:5},{n:7,walls:.16,boulders:2,min:5},{n:8,walls:.16,boulders:2,min:6},{n:8,walls:.18,boulders:2,min:7}],
   stickers:['🔄','🪨','🎱','🌀','⚖️','🧲']},
  {id:'shadow',name:'הצל הרודף',short:'הצל',rule:'צל שחור הולך בדיוק בעקבות שלך! אם תחזרי בדרך שבאת, תפגשי אותו, והוא ייקח ממך פנס. אספי את כל הפנסים 🏮 והגיעי אל הדלת, ואל תעצרי יותר מדי.',
   color:'#5a4b81',hex:'#5a4b81',deep:'#3c3157',goal:drawLantern,goalName:'הדלת',
   levels:[{n:7,loops:5,lights:2,delay:8,speed:700},{n:8,loops:6,lights:2,delay:7,speed:650},{n:9,loops:7,lights:3,delay:7,speed:600},{n:10,loops:8,lights:3,delay:6,speed:560},{n:11,loops:9,lights:4,delay:6,speed:520},{n:12,loops:10,lights:4,delay:5,speed:480}],
   stickers:['👣','🏮','🌑','🕯️','👻','🔦']},
  {id:'floors',name:'בניין הקומות',short:'הבניין',rule:'כל הקומות מוצגות זו לצד זו. מדרגות ▲ מעלות לאותו מקום בדיוק בקומה שמעל, ומדרגות ▼ מורידות. חור מפיל קומה למטה. היציאה בקומה העליונה!',
   color:'#3d405b',hex:'#3d405b',deep:'#272a3f',goal:drawRoof,goalName:'הגג',
   levels:[{m:4,floors:2,stairs:1,holes:0},{m:4,floors:2,stairs:2,holes:1},{m:5,floors:3,stairs:1,holes:1},{m:5,floors:3,stairs:2,holes:2},{m:6,floors:4,stairs:1,holes:2},{m:6,floors:4,stairs:2,holes:3}],
   stickers:['🏢','🪜','🛗','🏗️','🗝️','🌇']},
  {id:'escape',name:'חדר הבריחה',short:'בריחה',rule:'הדלת נעולה בקוד! אספי את הרמזים 📜: כל רמז נותן תרגיל לספרה אחת בצבע שלה. פתרי, הגיעי לדלת והקלידי את הקוד לפי סדר הצבעים.',
   color:'#8d6e63',hex:'#8d6e63',deep:'#5d4037',goal:drawCodeDoor,goalName:'הדלת',
   levels:[{n:7,digits:2},{n:8,digits:2},{n:9,digits:3},{n:10,digits:3},{n:11,digits:4},{n:12,digits:4}],
   stickers:['🔐','📜','🕵️‍♀️','🔎','🗺️','💡']},
  {id:'sheep',ui:{hint:1,undo:1},name:'עמק הכבשים',short:'הכבשים',rule:'כבשה בורחת צעד אחד ממך כשאת מתקרבת אליה, תמיד בקו ישר. היכנסי מאחוריה כדי לכוון אותה, והכניסי את כל הכבשים לדיר!',
   color:'#6a994e',hex:'#6a994e',deep:'#3f6d2c',goal:drawPen,goalName:'הדיר',
   levels:[{n:5,bush:.12,sheep:1,min:4},{n:6,bush:.12,sheep:1,min:7},{n:6,bush:.14,sheep:2,min:9},{n:7,bush:.14,sheep:2,min:11},{n:7,bush:.16,sheep:2,min:14},{n:7,bush:.16,sheep:3,min:14}],
   stickers:['🐑','🐕','🌾','🏡','🧶','🌄']},
  {id:'chef',name:'המטבח של השפית',short:'המטבח',rule:'המתכון כתוב למעלה. אספי את המצרכים לפי הסדר, והביאי אותם לסיר! כיריים אדומות 🔥 חמות, אז מחכים שיכבו.',
   color:'#f4a261',hex:'#f4a261',deep:'#c06c2b',goal:drawPot,goalName:'הסיר',
   levels:[{n:6,loops:3,ing:3,decoys:0,stoves:0,speed:1100},{n:7,loops:4,ing:3,decoys:2,stoves:1,speed:1100},{n:8,loops:5,ing:4,decoys:2,stoves:2,speed:1000},{n:9,loops:6,ing:4,decoys:3,stoves:3,speed:950},{n:10,loops:7,ing:5,decoys:3,stoves:4,speed:900},{n:11,loops:8,ing:5,decoys:4,stoves:5,speed:850}],
   stickers:['👩‍🍳','🍳','🥄','🧁','🍝','🥐']},
  {id:'memory',ui:{act:['👁️','להציץ']},name:'מבוך הזיכרון',short:'הזיכרון',rule:'תסתכלי טוב על המבוך! ברגע שזזים, הקירות נעלמים. קיר שנתקלים בו מופיע שוב, וכפתור 👁️ מחזיר את כל הקירות לרגע.',
   color:'#9d4edd',hex:'#9d4edd',deep:'#5a189a',goal:drawCrystal,goalName:'כדור הבדולח',
   levels:[{n:5,loops:1,peeks:3,near:1},{n:6,loops:2,peeks:3,near:1},{n:6,loops:2,peeks:2,near:0},{n:7,loops:3,peeks:2,near:0},{n:8,loops:3,peeks:2,near:0},{n:9,loops:4,peeks:2,near:0}],
   stickers:['🧠','👁️','🪄','🃏','💭','🎴']},
  {id:'spell',ui:{act:['🔊','להשמיע את המילה']},name:'מאייתים באנגלית',short:'איות',rule:'מה בתמונה? אספי את האותיות של המילה באנגלית לפי הסדר, ואז הדלת נפתחת. כפתור 🔊 אומר את המילה.',
   color:'#3a86ff',hex:'#3a86ff',deep:'#1d4ed8',goal:drawAbcDoor,goalName:'הדלת',
   levels:[{n:6,loops:3,len:3,show:1,decoys:0},{n:7,loops:3,len:3,show:0,decoys:2},{n:7,loops:4,len:4,show:1,decoys:2},{n:8,loops:4,len:4,show:0,decoys:3},{n:9,loops:5,len:5,show:1,decoys:3},{n:10,loops:5,len:5,show:0,decoys:4}],
   stickers:['🅰️','🐝','🦊','📖','✍️','🌍']},
  {id:'paint',ui:{hint:1,undo:1},name:'צובעים את הרצפה',short:'צבע',rule:'כל צעד צובע משבצת, ועל צבע רטוב אי אפשר לדרוך. צבעי את כל הרצפה! נתקעת? צעד אחורה ↩ או רמז 💡',
   color:'#ff70a6',hex:'#ff70a6',deep:'#c9184a',goal:drawPalette,goalName:'הרצפה',
   levels:[{n:4,wild:2,minRocks:1,maxRocks:3},{n:5,wild:1.5,minRocks:3,maxRocks:5},{n:5,wild:1,minRocks:0,maxRocks:2},{n:6,wild:1,minRocks:4,maxRocks:6},{n:6,wild:.6,minRocks:0,maxRocks:2},{n:7,wild:.6,minRocks:5,maxRocks:8}],
   stickers:['🎨','🖌️','🖍️','🖼️','🎭','🩷']},
  {id:'gravity',ui:{hint:1},name:'תחנת החלל',short:'כוח משיכה',rule:'רואים את התחנה מהצד. חץ למעלה הופך את כוח המשיכה ואת נופלת לתקרה, חץ למטה מחזיר. ימינה ושמאלה הולכים. זהירות ממוקשים 💥!',
   color:'#3a0ca3',hex:'#3a0ca3',deep:'#240672',goal:drawRocket,goalName:'החללית',
   levels:[{n:6,walls:.12,plat:1,spikes:0,min:3},{n:7,walls:.12,plat:2,spikes:0,min:4},{n:7,walls:.12,plat:2,spikes:1,min:5},{n:8,walls:.12,plat:3,spikes:2,min:6},{n:8,walls:.13,plat:3,spikes:3,min:7},{n:9,walls:.13,plat:4,spikes:4,min:8}],
   stickers:['🚀','🛰️','🌍','👩‍🚀','🌌','🪐']},
  {id:'snow',name:'ארמון השלג',short:'השלג',rule:'הדרך לארמון חסומה! מים 🌊 קופאים לגשר עם פתית שלג ❄️, וקיר קרח 🧊 נמס עם להבה 🔥. אספי אותם בדרך.',
   color:'#4895ef',hex:'#4895ef',deep:'#3a56b0',goal:drawSnowPalace,goalName:'ארמון השלג',
   levels:[{n:6,gates:1,melt:0},{n:7,gates:2,melt:0},{n:7,gates:1,melt:1},{n:8,gates:2,melt:1},{n:9,gates:3,melt:1},{n:10,gates:4,melt:1}],
   stickers:['☃️','🧊','❄️','👑','🦌','🏔️']},
  {id:'savanna',name:'ממלכת הסוואנה',short:'הסוואנה',rule:'חיות רעבות חוסמות את הדרך אל הסלע. הביאי לכל אחת את האוכל שהיא רוצה 💭 והיא תזוז. כשהאבק עולה »» עדר רץ בשורה, אז מחכים בצד!',
   color:'#e09f3e',hex:'#e09f3e',deep:'#9e6a1f',goal:drawSunRock,goalName:'סלע השמש',
   levels:[{n:6,gates:1,herds:0,period:5000},{n:7,gates:2,herds:0,period:5000},{n:7,gates:1,herds:1,period:5500},{n:8,gates:2,herds:1,period:5000},{n:9,gates:3,herds:2,period:4800},{n:10,gates:3,herds:2,period:4500}],
   stickers:['🌅','🦒','🐘','🌴','🥁','🐾']},
  {id:'lagoon',ui:{hint:1},name:'לגונת בנות הים',short:'הלגונה',rule:'ביבשה יש לך רגליים ובמים זנב של בת ים 🧜‍♀️. עוברים בין היבשה למים רק דרך צדף 🐚. שחי אל המערה!',
   color:'#2ec4b6',hex:'#2ec4b6',deep:'#1a8a80',goal:drawGrotto,goalName:'המערה',
   levels:[{n:6,pools:2,size:1.5,rock:.04,pads:3,min:6},{n:7,pools:2,size:1.8,rock:.06,pads:3,min:8},{n:7,pools:3,size:1.6,rock:.08,pads:3,min:9},{n:8,pools:3,size:2,rock:.08,pads:3,min:11},{n:9,pools:4,size:2,rock:.1,pads:4,min:13},{n:10,pools:4,size:2.2,rock:.1,pads:4,min:15}],
   stickers:['🧜‍♀️','🐚','🦀','🐠','💎','🌊']},
  {id:'carpet',ui:{hint:1,act:['🪔','משאלה']},name:'השטיח המעופף',short:'השטיח',rule:'השטיח עף עד שמשהו עוצר אותו. במנורה 🪔 יש משאלות: לוחצים עליה, בוחרים כיוון, והסלע הראשון שם נעלם!',
   color:'#9d4edd',hex:'#9d4edd',deep:'#6a2c9e',goal:drawPalace,goalName:'הארמון',
   levels:[{n:6,rock:.14,wishes:0,min:3},{n:7,rock:.15,wishes:0,min:4},{n:7,rock:.16,wishes:1,min:4},{n:8,rock:.17,wishes:1,min:5},{n:8,rock:.18,wishes:2,min:5},{n:9,rock:.18,wishes:2,min:6}],
   stickers:['🧞','🪔','🐪','🏜️','🕌','🌙']},
  {id:'ball',name:'הנשף של חצות',short:'הנשף',rule:'מצאי את נעל הזכוכית 👠 והגיעי לארמון לפני שהשעון מצלצל 12! כל צעד הוא דקה, ושרביט ✨ מחזיר את השעון אחורה.',
   color:'#c77dff',hex:'#c77dff',deep:'#7b2cbf',goal:drawBallCastle,goalName:'ארמון הנשף',
   levels:[{n:6,loops:3,wands:0,slack:14,bonus:6},{n:7,loops:3,wands:1,slack:10,bonus:6},{n:8,loops:4,wands:1,slack:8,bonus:6},{n:9,loops:5,wands:2,slack:6,bonus:5},{n:10,loops:5,wands:2,slack:5,bonus:5},{n:11,loops:6,wands:2,slack:4,bonus:5}],
   stickers:['👠','🎃','🕛','👗','🐭','💃']},
  {id:'toyroom',name:'הצעצועים מתעוררים',short:'הצעצועים',rule:'כשהילדה משחקת 🙈 זזים. כשהיא מסתכלת 👀 קופאים במקום! מתחת לשמיכה 🧺 אפשר לזוז תמיד. הגיעי לתיבת הצעצועים.',
   color:'#e76f51',hex:'#e76f51',deep:'#b04a30',goal:drawToyChest,goalName:'תיבת הצעצועים',
   levels:[{n:6,loops:3,hides:2,green:3500,red:1800},{n:7,loops:3,hides:2,green:3200,red:2000},{n:8,loops:4,hides:3,green:3000,red:2200},{n:9,loops:4,hides:3,green:2800,red:2400},{n:10,loops:5,hides:3,green:2600,red:2600},{n:11,loops:6,hides:4,green:2400,red:2800}],
   stickers:['🧸','🪆','🦖','🪀','🎁','🚂']},
  {id:'redhood',name:'כיפה אדומה',short:'כיפה אדומה',rule:'בדרך לבית של סבתא! קטפי לה פרחים 🌷 ביער. על השביל 🛤️ הזאב לא מתקרב, אבל כשיוצאים ליער הוא מתעורר ורודף. קטפי מהר וחזרי לשביל!',
   color:'#d62828',hex:'#d62828',deep:'#9d0208',goal:drawGrandma,goalName:'הבית של סבתא',
   levels:[{n:7,trees:.2,flowers:2,deep:1,wolves:0,speed:900},{n:7,trees:.2,flowers:2,deep:1,wolves:1,speed:900},{n:9,trees:.22,flowers:3,deep:1,wolves:1,speed:820},{n:9,trees:.25,flowers:3,deep:2,wolves:1,speed:740},{n:11,trees:.25,flowers:4,deep:2,wolves:2,speed:700},{n:11,trees:.28,flowers:4,deep:2,wolves:2,speed:640}],
   stickers:['🧺','🌷','🐺','👵','🍰','🌲']},
  {id:'hansel',name:'עמי ותמי',short:'עמי ותמי',rule:'היער חשוך! בדרך לבית הממתקים מפזרים פירורים, אבל הציפורים אוכלות את הישנים. מבית הממתקים 🍭 חוזרים הביתה 🏠, אז תזכרי את הדרך!',
   color:'#2d6a4f',hex:'#2d6a4f',deep:'#1b4332',goal:drawCandyHouse,goalName:'הבית',
   levels:[{n:6,loops:2,keep:99,light:2.6},{n:7,loops:2,keep:14,light:2.4},{n:7,loops:3,keep:10,light:2.2},{n:8,loops:3,keep:9,light:2},{n:9,loops:4,keep:8,light:1.9},{n:10,loops:4,keep:7,light:1.8}],
   stickers:['🍭','🍬','🐦','🍞','🏠','🍫']},
  {id:'pigs',name:'שלושת החזירונים',short:'החזירונים',rule:'הזאב בדרך! אספי לבנים 🧱 והביאי אותן לבית כדי לבנות בית חזק, לפני שהוא מגיע. כל צעד מקרב את הזאב 🐺.',
   color:'#e5989b',hex:'#e5989b',deep:'#b5838d',goal:drawPigHouse,goalName:'בית הלבנים',
   levels:[{n:6,loops:4,bricks:3,carry:1,slack:1.6},{n:7,loops:5,bricks:3,carry:2,slack:1.5},{n:7,loops:6,bricks:4,carry:2,slack:1.5},{n:8,loops:7,bricks:4,carry:2,slack:1.45},{n:8,loops:8,bricks:5,carry:3,slack:1.4},{n:9,loops:9,bricks:6,carry:3,slack:1.35}],
   stickers:['🐷','🧱','🌾','🪵','🐽','🏡']},
  {id:'beanstalk',name:'ג׳ק ופול הקסם',short:'פול הקסם',rule:'טיפסת על הפול אל הטירה של הענק! קחי את ביצת הזהב 🥚 וחזרי לפול. קרשים חורקים 🪵 עושים רעש, ואם יש יותר מדי רעש הענק מתעורר!',
   color:'#6a4c93',hex:'#6a4c93',deep:'#4a3470',goal:drawBeanTop,goalName:'הפול',
   levels:[{n:6,loops:3,creak:.15,limit:4,trap:0},{n:7,loops:3,creak:.2,limit:4,trap:0},{n:7,loops:4,creak:.25,limit:3,trap:1},{n:8,loops:4,creak:.28,limit:3,trap:1},{n:9,loops:5,creak:.3,limit:3,trap:1},{n:10,loops:6,creak:.32,limit:3,trap:1}],
   stickers:['🌱','🥚','👹','☁️','🪙','🎻']},
  {id:'thorns',name:'היפהפייה הנרדמת',short:'הקוצים',rule:'קוצים מסביב לטירה! נכנסים לקוץ כדי לחתוך אותו 🗡️, ואז עוברים. הקוצים צומחים שוב, אז רצים מאחו לאחו 🌼 ומגיעים למגדל.',
   color:'#c9184a',hex:'#c9184a',deep:'#800f2f',goal:drawCastleTower,goalName:'המגדל',
   levels:[{n:6,gap:2,meadows:3,stones:2,regrow:7000},{n:7,gap:2,meadows:3,stones:3,regrow:6000},{n:7,gap:3,meadows:3,stones:4,regrow:5500},{n:8,gap:3,meadows:4,stones:5,regrow:5000},{n:9,gap:3,meadows:4,stones:6,regrow:4800},{n:10,gap:4,meadows:5,stones:7,regrow:5000}],
   stickers:['🌹','🗡️','🏰','😴','🦉','👑']},
  {id:'match3',ui:{hint:1,act:['🔄','לבחור סוכרייה'],key:1,still:1},name:'סוכריות בשורה',short:'סוכריות',rule:'מחליפים שתי סוכריות שכנות (מחליקים אצבע, או בחצים: עומדים, לוחצים 🔄 ואז חץ) כדי לסדר 3 באותו צבע בשורה. 4 בשורה = סוכריית פסים שמנקה שורה, 5 = פצצת שוקולד! עשי את המשימה למעלה לפני שנגמרים המהלכים.',
   color:'#ff70a6',hex:'#ff70a6',deep:'#c9184a',goal:(c,x,y,r)=>drawCandy(c,x,y,r*.85,0,0,0),goalName:'המשימה',
   levels:[{n:7,colors:4,collect:15,moves:20},{n:7,colors:5,collect:18,moves:20},{n:7,colors:5,jelly:10,moves:22},{n:8,colors:5,collect:15,jelly:8,moves:24},{n:8,colors:5,drops:2,moves:30},{n:8,colors:5,jelly:12,drops:2,moves:32}],
   stickers:['🍬','🍭','🍫','🧁','🍩','🍒']},
  {id:'blocks',ui:{hint:1,act:['🧩','לשים את הצורה'],key:1,still:1},name:'פאזל הקוביות',short:'קוביות',rule:'גוררים צורה מלמטה אל הלוח (או: בוחרים בחצים ושמים בכפתור 🧩). נגיעה נוספת בצורה מסובבת אותה 🔄. שורה או טור מלאים נעלמים! נקי את מספר השורות שלמעלה.',
   color:'#1982c4',hex:'#1982c4',deep:'#14213d',goal:(c,x,y,r)=>{['#ff595e','#ffca3a','#8ac926','#1982c4'].forEach((col,i)=>{c.fillStyle=col;rrect(c,x-r*.8+(i%2)*r*.82,y-r*.8+Math.floor(i/2)*r*.82,r*.76,r*.76,r*.15);c.fill();});},goalName:'הלוח',
   levels:[{lines:3,fill:.15,pool:'small'},{lines:5,fill:.2,pool:'small'},{lines:6,fill:.2,pool:'big'},{lines:8,fill:.25,pool:'big'},{lines:10,fill:.25,pool:'huge'},{lines:12,fill:.3,pool:'huge'}],
   stickers:['🧩','🟥','🟦','🟨','🟩','💎']},
  {id:'broom',name:'טיסה על מטאטא',short:'מטאטא',rule:'המטאטא טס ימינה לבד! חץ למעלה ולמטה כדי לעבור בתוך כל הטבעות 💫 ולא להיתקע בעננים ☁️. חץ ימינה = מהר יותר.',
   color:'#48cae4',hex:'#48cae4',deep:'#0077b6',goal:drawWizTower,goalName:'המגדל',
   levels:[{n:7,clouds:.1,lat:1,rings:2,birds:0,speed:950},{n:8,clouds:.12,lat:1,rings:3,birds:0,speed:900},{n:8,clouds:.15,lat:1,rings:3,birds:1,speed:850},{n:9,clouds:.15,lat:2,rings:4,birds:1,speed:800},{n:10,clouds:.17,lat:2,rings:4,birds:2,speed:760},{n:11,clouds:.18,lat:2,rings:5,birds:2,speed:720}],
   stickers:['🧹','💫','☁️','🐦','🏆','🌤️']},
  {id:'stairs',ui:{step:1},name:'המדרגות הזזות',short:'מדרגות',rule:'בטירה יש מדרגות שמסתובבות כל כמה שניות 🪜: פעם לרוחב ופעם לאורך. עולים עליהן רק כשהן בכיוון שלך. כשהן מהבהבות, הן עומדות להסתובב!',
   color:'#8d6e63',hex:'#8d6e63',deep:'#5d4037',goal:drawWizTower,goalName:'המגדל',
   levels:[{n:6,loops:0,stairs:1,period:3200},{n:7,loops:0,stairs:2,period:3000},{n:7,loops:1,stairs:2,period:2700},{n:8,loops:1,stairs:3,period:2500},{n:8,loops:2,stairs:4,period:2300},{n:9,loops:2,stairs:5,period:2200}],
   stickers:['🪜','🕯️','🖼️','🏰','🗝️','🌙']},
  {id:'potion',name:'שיעור שיקויים',short:'שיקויים',rule:'אספי את המצרכים של המתכון 🧪 (רק מה שכתוב למעלה!), בשלי אותם בקדרה, והשיקוי יעזור לך לעבור דרך וילונות הקסם 🔮.',
   color:'#7b2cbf',hex:'#7b2cbf',deep:'#3c096c',goal:drawMagicDoor,goalName:'הדלת',
   levels:[{n:6,ings:2,decoys:0,barriers:1},{n:7,ings:3,decoys:1,barriers:1},{n:7,ings:3,decoys:2,barriers:2},{n:8,ings:4,decoys:2,barriers:2},{n:8,ings:4,decoys:3,barriers:3},{n:9,ings:5,decoys:3,barriers:3}],
   stickers:['🧪','🍄','🌿','🐸','🔮','✨']},
  {id:'owlpost',ui:{step:1},name:'דואר הינשופים',short:'ינשופים',rule:'מסרי כל מכתב ✉️ למגדל בצבע שלו. כל צעד מעייף את הינשוף 🦉: הוא נח בעצים 🌳, בבית הינשופים, ובכל מגדל שמקבל מכתב.',
   color:'#6c584c',hex:'#6c584c',deep:'#3f3229',goal:drawOwlery,goalName:'בית הינשופים',
   levels:[{n:7,loops:4,letters:2,perches:1,slack:6},{n:8,loops:4,letters:2,perches:1,slack:5},{n:8,loops:5,letters:3,perches:2,slack:4},{n:9,loops:5,letters:3,perches:2,slack:3},{n:10,loops:6,letters:4,perches:3,slack:3},{n:11,loops:6,letters:4,perches:3,slack:2}],
   stickers:['🦉','✉️','📜','🌳','📮','🎓']},
  {id:'flykeys',name:'המפתחות המעופפים',short:'מפתחות',rule:'מפתחות עם כנפיים עפים בחדר 🗝️! הדלת מראה באיזה צבע וסדר צריך אותם. תפסי את הנכון (מפתח לא נכון בורח), ואז לדלת.',
   color:'#8ec5fc',hex:'#8e9efc',deep:'#5a67d8',goal:drawMagicDoor,goalName:'הדלת',
   levels:[{n:6,pillars:.08,keys:2,need:1,speed:1200,shy:0},{n:7,pillars:.1,keys:3,need:1,speed:1100,shy:0},{n:7,pillars:.1,keys:3,need:2,speed:1000,shy:0},{n:8,pillars:.12,keys:4,need:2,speed:950,shy:1},{n:9,pillars:.12,keys:4,need:3,speed:900,shy:1},{n:9,pillars:.14,keys:5,need:3,speed:850,shy:1}],
   stickers:['🗝️','🔑','🦋','🚪','💜','🌀']},
  {id:'wand',ui:{act:['🪄','להטיל לחש'],step:1},name:'שיעור לחשים',short:'לחשים',rule:'דלתות קסומות 🚪 נפתחות רק בלחש! עומדים ליד הדלת, לוחצים 🪄, ולוחצים על החיצים של הלחש לפי הסדר (בכפתורי החצים או בהחלקת אצבע).',
   color:'#3c096c',hex:'#5a189a',deep:'#240046',goal:drawWizTower,goalName:'המגדל',
   levels:[{n:6,doors:1,len:2},{n:6,doors:2,len:2},{n:7,doors:2,len:3},{n:7,doors:3,len:3},{n:8,doors:3,len:4},{n:9,doors:4,len:4}],
   stickers:['🪄','⭐','🌟','📖','🎩','🐇']},
  {id:'match3b',ui:{hint:1,act:['🔄','לבחור סוכרייה'],key:1,still:1},name:'ממלכת השוקולד',short:'שוקולד',rule:'עוד סוכריות! 🔒 סוכרייה נעולה נפתחת כששורה עוברת דרכה. 🍫 שוקולד נמס כששורה נוצרת לידו (ולפעמים הוא גדל!). צורת L או T = סוכרייה עטופה 🎁, ושתי סוכריות מיוחדות ביחד = פיצוץ ענק!',
   color:'#8d5524',hex:'#8d5524',deep:'#5e3b1f',goal:(c,x,y,r)=>drawCandy(c,x,y,r*.85,-5,0,0),goalName:'המשימה',
   levels:[{n:7,colors:5,cages:5,moves:20},{n:7,colors:5,choc:4,moves:22},{n:8,colors:5,choc:6,cages:4,moves:24},{n:8,colors:5,choc:4,spread:1,moves:24},{n:8,colors:5,jelly:8,cages:5,moves:30},{n:8,colors:5,choc:6,spread:1,drops:2,moves:30}],
   stickers:['🍫','🔒','🍭','🍬','🧁','🎂']},
  {id:'blockscore',ui:{hint:1,act:['🧩','לשים את הצורה'],key:1,still:1},name:'שיא הקוביות',short:'שיא',rule:'משחק בלי סוף! שמים צורות, ממלאים שורות, ואוספים נקודות ⭐. כמה שורות ביחד או כמה תורות ברצף 🔥 = בונוס, ולוח נקי לגמרי = 300! הגיעי ליעד הנקודות, ונסי לשבור את השיא שלך 🏆.',
   color:'#ff924c',hex:'#f77f00',deep:'#b35900',goal:(c,x,y,r)=>{c.font=(r*1.4)+'px sans-serif';c.textAlign='center';c.textBaseline='middle';c.fillText('🏆',x,y);},goalName:'היעד',
   levels:[{target:300,pool:'small'},{target:600,pool:'big'},{target:1000,pool:'big'},{target:1500,pool:'huge'},{target:2200,pool:'huge'},{target:3000,pool:'huge'}],
   stickers:['🏆','🔥','💯','🧱','⭐','🎯']},
  {id:'giant',name:'המבוך הענק',short:'ענק',rule:'המבוך הזה כל כך גדול שהוא לא נכנס במסך! המסך זז יחד איתך. במפה הקטנה 🗺️ רואים איפה את 🟣, איפה הכוכבים 🟡 ואיפה המזרקה 🔴.',
   color:'#2d6a4f',hex:'#40916c',deep:'#1b4332',goal:drawFountain,goalName:'המזרקה',
   levels:[{n:12,loops:3,view:8},{n:15,loops:4,view:8},{n:18,loops:5,view:9},{n:21,loops:7,view:9},{n:25,loops:9,view:9},{n:30,loops:12,view:9}],
   stickers:['🌿','🌼','🧭','🗺️','🐌','⛲']},
  {id:'firetruck',name:'כבאית ההצלה',short:'כבאית',rule:'נוסעים אל כל השריפות 🔥 ומכבים אותן. כל שריפה צריכה מים מהמיכל 💧. נגמרו המים? ממלאים בברז כיבוי או בתחנה. בסוף חוזרים לתחנה!',
   color:'#d62828',hex:'#e5383b',deep:'#9d0208',goal:drawFireStation,goalName:'תחנת הכיבוי',
   levels:[{n:6,loops:3,fires:2,hydrants:1,cap:3},{n:7,loops:3,fires:3,hydrants:1,cap:2},{n:8,loops:4,fires:3,hydrants:2,cap:2},{n:9,loops:5,fires:4,hydrants:2,cap:2},{n:10,loops:6,fires:5,hydrants:2,cap:2},{n:11,loops:7,fires:6,hydrants:3,cap:2}],
   stickers:['🚒','🧯','⛑️','🚨','🪜','🧑‍🚒']},
  {id:'schoolbus',ui:{step:1},name:'אוטובוס התלמידים',short:'אוטובוס',rule:'אוספים את הילדים מהתחנות לפי המספרים 1, 2, 3… ואז לבית הספר 🏫. ברחוב עם חץ ⛔ נוסעים רק לכיוון החץ!',
   color:'#e09f3e',hex:'#f4a261',deep:'#bc6c25',goal:drawSchool,goalName:'בית הספר',
   levels:[{n:6,loops:4,stops:2,oneway:3},{n:7,loops:5,stops:3,oneway:5},{n:8,loops:6,stops:3,oneway:7},{n:9,loops:8,stops:4,oneway:9},{n:10,loops:9,stops:4,oneway:12},{n:11,loops:11,stops:5,oneway:15}],
   stickers:['🚌','🎒','✏️','🛑','🔔','🧃']},
  {id:'train',ui:{step:1},name:'רכבת המטענים',short:'רכבת',rule:'הרכבת נוסעת לבד! 🚂 החצים בוחרים לאן היא תפנה בצומת הבא. אוספים את כל המטען 📦 ומגיעים לתחנה. בצומת בלי בחירה הרכבת מחכה לך.',
   color:'#1d3557',hex:'#457b9d',deep:'#1d3557',goal:drawTrainStation,goalName:'התחנה',
   levels:[{n:6,loops:5,cargo:1,speed:780},{n:7,loops:6,cargo:2,speed:720},{n:8,loops:7,cargo:2,speed:660},{n:9,loops:9,cargo:3,speed:610},{n:10,loops:10,cargo:3,speed:560},{n:11,loops:12,cargo:4,speed:520}],
   stickers:['🚂','🎫','⏰','🚃','🧳','🌉']},
  {id:'parking',ui:{hint:1,undo:1,act:['🔄','מכונית אחרת'],key:1,still:1},name:'פקק בחניון',short:'חניון',rule:'המכונית האדומה רוצה לצאת ➡️ מזיזים מכוניות קדימה ואחורה (כל מכונית רק בכיוון שלה) עד שהדרך פנויה. גוררים מכונית באצבע, או בוחרים ב־🔄 ומזיזים בחצים.',
   color:'#495057',hex:'#6c757d',deep:'#343a40',goal:drawParkingSign,goalName:'היציאה',
   levels:[{cars:5,trucks:.1,lo:1,hi:3},{cars:6,trucks:.15,lo:2,hi:4},{cars:7,trucks:.2,lo:3,hi:6},{cars:8,trucks:.25,lo:5,hi:8},{cars:9,trucks:.25,lo:7,hi:10},{cars:10,trucks:.3,lo:9,hi:13}],
   stickers:['🅿️','🚗','🚙','🚕','🔑','🚧']},
  {id:'lights',ui:{step:1},name:'עיר הרמזורים',short:'רמזורים',rule:'ברמזור 🚦 עוברים רק בירוק! באדום עוצרים ומחכים. צהוב = עוד רגע מתחלף. הגיעי אל גן השעשועים.',
   color:'#2a9d8f',hex:'#52b788',deep:'#2d6a4f',goal:drawPlayground,goalName:'גן השעשועים',
   levels:[{n:6,loops:3,lights:2,extra:1,period:4400},{n:7,loops:4,lights:3,extra:1,period:4200},{n:8,loops:5,lights:3,extra:2,period:4000},{n:9,loops:6,lights:4,extra:3,period:3800},{n:10,loops:7,lights:5,extra:3,period:3600},{n:11,loops:8,lights:6,extra:4,period:3400}],
   stickers:['🚦','🚸','🛴','🚲','🦺','🧢']},
  {id:'race',name:'מרוץ המכוניות',short:'מרוץ',rule:'3, 2, 1… צאו! מגיעים לדגל 🏁 לפני המכונית הירוקה. ⚡ טורבו = קפיצות כפולות. 🛢️ שמן = המכונית מסתובבת רגע, אז עדיף לעקוף.',
   color:'#c1121f',hex:'#ef476f',deep:'#9d0208',goal:drawFinishFlag,goalName:'קו הסיום',
   levels:[{n:6,loops:4,turbo:1,oil:1,speed:950},{n:7,loops:5,turbo:1,oil:2,speed:860},{n:8,loops:6,turbo:2,oil:2,speed:780},{n:9,loops:7,turbo:2,oil:3,speed:720},{n:10,loops:8,turbo:2,oil:3,speed:660},{n:11,loops:9,turbo:3,oil:4,speed:600}],
   stickers:['🏎️','🏆','🥇','🛞','🧤','🎖️']}
];
// world indexes from world ids (a world's index is its save key, so worlds are only ever added at the end)
function wids(...a){return a.map(id=>{const i=WORLDS.findIndex(W=>W.id===id);if(i<0)throw new Error('no world '+id);return i;});}
// characters are unlocked by finishing a world, named by its id
CHARS.forEach(c=>{if(c.unlock!=null)c.unlock=wids(c.unlock)[0];});
function levelCount(){return WORLDS.reduce((a,W)=>a+W.levels.length,0);}

