const {chromium}=require('playwright');(async()=>{const b=await chromium.launch();const p=await b.newPage({viewport:{width:390,height:844}});const errs=[];p.on('pageerror',e=>errs.push(e.message+' '+(e.stack||'').split('\n')[1]));
const u='file://'+__dirname+'/../dist/page.html';await p.goto(u);await p.evaluate(()=>localStorage.setItem('journey_tut',JSON.stringify(window.__T.WORLDS.map(w=>w.id))));await p.goto(u);
const out=[],E=(f,a)=>p.evaluate(f,a);
const st=async lbl=>out.push(lbl+': '+(await p.isVisible('#bCoach')?await p.textContent('#bCoachT'):'(no coach)')+' | tab '+await E(()=>document.querySelector('#bTabs [aria-pressed="true"]').dataset.tab)+' tool '+await E(()=>(document.querySelector('#bTools [aria-pressed="true"]')||{}).dataset?.t)+' | hl '+await E(()=>[...document.querySelectorAll('.coach-hl')].map(e=>e.id||e.dataset.t||e.dataset.tab).join(',')));
let box,cs;const geo=async()=>{box=await E(()=>{const r=document.getElementById('bCv').getBoundingClientRect();return [r.left,r.top,r.width];});cs=box[2]/8;};const C=(x,y)=>[box[0]+(x+.5)*cs,box[1]+(y+.5)*cs];
await p.click('#buildOpen');await p.click('#bNewBtn');await p.waitForTimeout(200);await st('0 start');await p.screenshot({path:'co0.png'});
await geo();await p.mouse.move(...C(2,0));await p.mouse.down();for(let y=1;y<=5;y++)await p.mouse.move(...C(2,y),{steps:3});await p.mouse.up();await p.waitForTimeout(200);await st('1a still walls');await p.click('#bCoachNext');await st('1 after walls');
await geo();await p.mouse.click(...C(0,7));await p.waitForTimeout(200);await st('2 after start');
await geo();await p.mouse.click(...C(7,0));await p.waitForTimeout(200);await st('3 after goal');
await geo();for(const c of [[1,1],[5,5],[6,2]])await p.mouse.click(...C(...c));await p.waitForTimeout(200);await st('4 after stars');await p.screenshot({path:'co4.png'});
await p.click('#bRobotBtn');await p.waitForTimeout(2500);await st('5 after robot');
await p.click('#bPlayBtn');await p.waitForTimeout(500);await p.click('#fsExit');await p.waitForTimeout(400);await st('6 back from play');await p.screenshot({path:'co6.png'});
await p.click('#bCoachNext');await st('7 after finish');
await p.click('#buildBack');await p.click('#bNewBtn');await p.waitForTimeout(200);await st('8 second maze');
await p.click('#bHelpBtn');await st('9 help');await p.click('#bCoachNext');await st('10 skip');await p.click('#bCoachX');await st('11 closed');
await p.click('#bTabs [data-tab="special"]');await st('12 special first');await p.screenshot({path:'co12.png'});await p.click('#bCoachNext');await st('13 got it');
await p.click('#bTabs [data-tab="walls"]');await p.click('#bTabs [data-tab="special"]');await st('14 special again');
await p.click('#bTheme button:nth-child(3)');await st('15 space theme on special');await p.click('#bCoachNext');
await p.click('#bTabs [data-tab="deco"]');await st('16 deco first');
await p.setViewportSize({width:844,height:390});await p.click('#bHelpBtn');await p.waitForTimeout(200);await p.screenshot({path:'co_land.png'});
console.log(out.join('\n'));console.log('errors',[...new Set(errs)]);await b.close();})();
